# Generated by Django 3.2.6 on 2021-08-17 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_activity', models.DateTimeField(verbose_name='Начало активности')),
                ('end_of_activity', models.DateTimeField(verbose_name='Конец активности')),
                ('type_active', models.CharField(choices=[('walking', 'Ходьба'), ('running', 'Бег'), ('cycling', 'Велосипед')], max_length=8, verbose_name='Тип активности')),
                ('distance', models.FloatField(verbose_name='Дистанция в метрах')),
                ('calorie_count', models.FloatField(verbose_name='Количество калорий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
